# Shell variables
# Generated by 'wal'
wallpaper='/home/lynla_13/Pictures/RIN/768294.jpg'

# Special
background='#1c1234'
foreground='#f1ede2'
cursor='#f1ede2'

# Colors
color0='#1c1234'
color1='#546BA4'
color2='#AA78A0'
color3='#6A99B9'
color4='#B5B2B3'
color5='#A1CDD0'
color6='#DDD5D3'
color7='#f1ede2'
color8='#a8a59e'
color9='#546BA4'
color10='#AA78A0'
color11='#6A99B9'
color12='#B5B2B3'
color13='#A1CDD0'
color14='#DDD5D3'
color15='#f1ede2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
