# Shell variables
# Generated by 'wal'
wallpaper='/home/lynla_13/Pictures/RIN/763745.png'

# Special
background='#251e1a'
foreground='#eae7e0'
cursor='#eae7e0'

# Colors
color0='#251e1a'
color1='#5E7887'
color2='#71878C'
color3='#788EA4'
color4='#6C8BC3'
color5='#929C9F'
color6='#D8C4AB'
color7='#eae7e0'
color8='#a3a19c'
color9='#5E7887'
color10='#71878C'
color11='#788EA4'
color12='#6C8BC3'
color13='#929C9F'
color14='#D8C4AB'
color15='#eae7e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
