# Shell variables
# Generated by 'wal'
wallpaper='/home/lynla_13/Pictures/RIN/1228736.png'

# Special
background='#2e1b25'
foreground='#f3e3c7'
cursor='#f3e3c7'

# Colors
color0='#2e1b25'
color1='#B38B66'
color2='#E09D69'
color3='#F7CA75'
color4='#937988'
color5='#AE9894'
color6='#DFAF8F'
color7='#f3e3c7'
color8='#aa9e8b'
color9='#B38B66'
color10='#E09D69'
color11='#F7CA75'
color12='#937988'
color13='#AE9894'
color14='#DFAF8F'
color15='#f3e3c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
