--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lynla_13/Pictures/RIN/856223.jpg"

-- Special
background="#24252d"
foreground="#e8e8e7"
cursor="#e8e8e7"

-- Colors
color0="#24252d"
color1="#2BA8DA"
color2="#57B3CC"
color3="#F0A8A4"
color4="#F6E8AA"
color5="#BBBAC7"
color6="#FBCED1"
color7="#e8e8e7"
color8="#a2a2a1"
color9="#2BA8DA"
color10="#57B3CC"
color11="#F0A8A4"
color12="#F6E8AA"
color13="#BBBAC7"
color14="#FBCED1"
color15="#e8e8e7"
