--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lynla_13/Pictures/RIN/1228736.png"

-- Special
background="#2e1b25"
foreground="#f3e3c7"
cursor="#f3e3c7"

-- Colors
color0="#2e1b25"
color1="#B38B66"
color2="#E09D69"
color3="#F7CA75"
color4="#937988"
color5="#AE9894"
color6="#DFAF8F"
color7="#f3e3c7"
color8="#aa9e8b"
color9="#B38B66"
color10="#E09D69"
color11="#F7CA75"
color12="#937988"
color13="#AE9894"
color14="#DFAF8F"
color15="#f3e3c7"
