--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lynla_13/Pictures/RIN/768294.jpg"

-- Special
background="#1c1234"
foreground="#f1ede2"
cursor="#f1ede2"

-- Colors
color0="#1c1234"
color1="#546BA4"
color2="#AA78A0"
color3="#6A99B9"
color4="#B5B2B3"
color5="#A1CDD0"
color6="#DDD5D3"
color7="#f1ede2"
color8="#a8a59e"
color9="#546BA4"
color10="#AA78A0"
color11="#6A99B9"
color12="#B5B2B3"
color13="#A1CDD0"
color14="#DDD5D3"
color15="#f1ede2"
